name: Deploy to EC2 using Docker

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 레포지토리 체크아웃
        uses: actions/checkout@v3

      - name: Docker Buildx 설정
        uses: docker/setup-buildx-action@v2

      - name: Docker Hub 로그인
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Docker 이미지 빌드 및 Push (캐시 없이 새로 빌드)
        run: |
          docker buildx build --no-cache -t app .
          docker tag app ${{ secrets.DOCKER_USERNAME }}/app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/app:latest

      - name: SSH를 이용해 EC2에 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker stop app || true
            sudo docker rm app || true
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/app:latest
            sudo docker run -d --name app -p 3000:3000 --env-file /home/ubuntu/.env ${{ secrets.DOCKER_USERNAME }}/app:latest
